spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: friday-consumer
      enable-auto-commit: true
      auto-commit-interval: 100ms
      properties:
        session.timeout.ms: 15000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      retries: 0 #若设置大于0的值，客户端会将发送失败的记录重新发送
      batch-size: 16384 #当将多个记录被发送到同一个分区时， Producer 将尝试将记录组合到更少的请求中。这有助于提升客户端和服务器端的性能。这个配置控制一个批次的默认大小（以字节为单位）。16384是缺省的配置
      buffer-memory: 33554432 #Producer 用来缓冲等待被发送到服务器的记录的总字节数，33554432是缺省配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer #关键字的序列化类
      value-serializer: org.apache.kafka.common.serialization.StringSerializer #值的序列化类

#  activemq:
#    broker-url: tcp://127.0.0.1:61616
#    user: laohui
#    password: laohui
#    packages:
#      trust-all: true

server:
  servlet:
    encoding:
      force: true
  port: ${APP_PORT:8010}

shiro:
  web:
    enabled: true
#  enabled: true
#  loginUrl: /login
#  sessionManager:
#    sessionIdCookieEnabled: true
#    sessionIdUrlRewritingEnabled: true
dubbo:
  application:
    name: friday-server # 消息者名字
  registry:
    address: zookeeper://172.16.2.136:2181 # 注册中心地址
    check: false
  protocol:
    port: 9091
  consumer:
    check: false
  provider:
    host: 172.16.2.136

